dependencies:
  - name: mysql
    version: 1.6.2
    repository: https://mirror.azure.cn/kubernetes/charts/
    condition: mysql.enabled
  - name: redis
    version: 10.3.0
    repository: https://mirror.azure.cn/kubernetes/charts/
    condition: redis.enabled
